services:
  anotherbackendservice:
    image: ${DOCKER_REGISTRY-}anotherbackendservice
    build:
      context: .
      dockerfile: anotherbackendservice/Dockerfile

  backendservices:
    image: ${DOCKER_REGISTRY-}backendservices
    build:
      context: .
      dockerfile: backendservices/Dockerfile

