services:
  anotherbackendservice:
    image: ${DOCKER_REGISTRY-}anotherbackendservice
    build:
      context: .
      dockerfile: anotherbackendservice/Dockerfile

  backendservices:
    image: ${DOCKER_REGISTRY-}backendservices
    build:
      context: .
      dockerfile: backendservices/Dockerfile

  database:
    image: ${DOCKER_REGISTRY-}datbase
    build:
      context: .
      dockerfile: database.Dockerfile
    environment:
     # - POSTGRES_DB=sample_database
     # - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=mysecretpassword
    volumes:
     - ./container-storage/pg_data:/var/lib/postgresql/data
     # - my_new_pg_data:/var/lib/postgresql/data
    ports:
     - 5500:5432

  cache:
    image: redis:7.4.1-alpine
    restart: always
    command: redis-server
    ports:
     - '6379:6379'
    volumes:
     - ./container-storage/redis_data:/data


# volumes:
    # redis-data-volume:
    # my_new_pg_data: