name: Build and Deploy Docker Images

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  ACR_NAME: ${{ vars.ACR_NAME }}
  RESOURCE_GROUP: ${{ vars.RESOURCE_GROUP }}
  # Production environment settings
  ENVIRONMENT: Production
  ENV_TAG: prod
  BACKEND_APP_NAME: ${{ vars.BACKEND_APP_NAME }}
  ANOTHER_BACKEND_APP_NAME: ${{ vars.ANOTHER_BACKEND_APP_NAME }}
  FRONTEND_APP_NAME: ${{ vars.FRONTEND_APP_NAME }}
  APP_SERVICE_PLAN: ${{ vars.APP_SERVICE_PLAN }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    name: Build and Push
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2
      
      - name: 'Login to Azure'
        uses: Azure/login@v2.2.0
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: Login to Azure Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.ACR_NAME }}.azurecr.io
          username: ${{ fromJson(secrets.AZURE_CREDENTIALS).clientId }}
          password: ${{ fromJson(secrets.AZURE_CREDENTIALS).clientSecret }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push primary backend services
        uses: docker/build-push-action@v6
        with:
          context: ${{ github.workspace }}/services
          file: ${{ github.workspace }}/services/backendservices/Dockerfile
          push: true
          build-args: |
            BUILD_CONFIGURATION=${{ env.ENVIRONMENT }}
          tags: |
            ${{ env.ACR_NAME }}.azurecr.io/backendservices:${{ env.ENV_TAG }}-${{ github.run_number }}
            ${{ env.ACR_NAME }}.azurecr.io/backendservices:latest-${{ env.ENV_TAG }}

      - name: Build and push secondary backend services
        uses: docker/build-push-action@v6
        with:
          context: ${{ github.workspace }}/services
          file: ${{ github.workspace }}/services/anotherbackendservices/Dockerfile
          push: true
          build-args: |
            BUILD_CONFIGURATION=${{ env.ENVIRONMENT }}
          tags: |
            ${{ env.ACR_NAME }}.azurecr.io/anotherbackendservices:${{ env.ENV_TAG }}-${{ github.run_number }}
            ${{ env.ACR_NAME }}.azurecr.io/anotherbackendservices:latest-${{ env.ENV_TAG }}

      - name: Build and push frontend
        uses: docker/build-push-action@v6
        with:
          context: ${{ github.workspace }}/frontend
          file: ${{ github.workspace }}/frontend/Dockerfile
          push: true
          build-args: |
            BUILD_CONFIGURATION=${{ env.ENVIRONMENT }}
          tags: |
            ${{ env.ACR_NAME }}.azurecr.io/frontend:${{ env.ENV_TAG }}-${{ github.run_number }}
            ${{ env.ACR_NAME }}.azurecr.io/frontend:latest-${{ env.ENV_TAG }}

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    name: Deploy to Azure Web App
    # environment: production
    
    steps:
      - name: 'Login to Azure'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      # Configure and deploy primary backend app
      - name: 'Configure Primary Backend App Service Settings'
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az webapp config appsettings set \
              --resource-group ${{ env.RESOURCE_GROUP }} \
              --name ${{ env.BACKEND_APP_NAME }} \
              --settings \
                ASPNETCORE_ENVIRONMENT=${{ env.ENVIRONMENT }} \
                WEBSITES_PORT=8080 \
                DOCKER_REGISTRY_SERVER_URL="https://${{ env.ACR_NAME }}.azurecr.io" \
                DOCKER_REGISTRY_SERVER_USERNAME="${{ fromJson(secrets.AZURE_CREDENTIALS).clientId }}" \
                DOCKER_REGISTRY_SERVER_PASSWORD="${{ fromJson(secrets.AZURE_CREDENTIALS).clientSecret }}" \
 
            az webapp config connection-string set \
              --resource-group ${{ env.RESOURCE_GROUP }} \
              --name ${{ env.BACKEND_APP_NAME }} \
              --settings SQL_Server_Database='${{ secrets.SQL_CONNECTION_STRING }}' \
              --connection-string-type SQLAzure
      
      - name: 'Deploy Primary Backend to Azure Web App'
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.BACKEND_APP_NAME }}
          images: '${{ env.ACR_NAME }}.azurecr.io/backendservices:${{ env.ENV_TAG }}-${{ github.run_number }}'

      # Configure and deploy secondary backend app
      - name: 'Configure Secondary Backend App Service Settings'
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az webapp config appsettings set \
              --resource-group ${{ env.RESOURCE_GROUP }} \
              --name ${{ env.ANOTHER_BACKEND_APP_NAME }} \
              --settings \
                ASPNETCORE_ENVIRONMENT=${{ env.ENVIRONMENT }} \
                WEBSITES_PORT=8080 \
                DOCKER_REGISTRY_SERVER_URL="https://${{ env.ACR_NAME }}.azurecr.io" \
                DOCKER_REGISTRY_SERVER_USERNAME="${{ fromJson(secrets.AZURE_CREDENTIALS).clientId }}" \
                DOCKER_REGISTRY_SERVER_PASSWORD="${{ fromJson(secrets.AZURE_CREDENTIALS).clientSecret }}" \
 
            az webapp config connection-string set \
              --resource-group ${{ env.RESOURCE_GROUP }} \
              --name ${{ env.ANOTHER_BACKEND_APP_NAME }} \
              --settings SQL_Server_Database='${{ secrets.SQL_CONNECTION_STRING }}' \
              --connection-string-type SQLAzure
      
      - name: 'Deploy Secondary Backend to Azure Web App'
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.ANOTHER_BACKEND_APP_NAME }}
          images: '${{ env.ACR_NAME }}.azurecr.io/anotherbackendservices:${{ env.ENV_TAG }}-${{ github.run_number }}'

      # Configure and deploy frontend app
      - name: 'Configure Frontend App Service Settings'
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az webapp config appsettings set \
              --resource-group ${{ env.RESOURCE_GROUP }} \
              --name ${{ env.FRONTEND_APP_NAME }} \
              --settings \
                WEBSITES_PORT=80 \
                DOCKER_REGISTRY_SERVER_URL="https://${{ env.ACR_NAME }}.azurecr.io" \
                DOCKER_REGISTRY_SERVER_USERNAME="${{ fromJson(secrets.AZURE_CREDENTIALS).clientId }}" \
                DOCKER_REGISTRY_SERVER_PASSWORD="${{ fromJson(secrets.AZURE_CREDENTIALS).clientSecret }}" \
                API_URL="https://${{ env.BACKEND_APP_NAME }}.azurewebsites.net" \
                ANOTHER_API_URL="https://${{ env.ANOTHER_BACKEND_APP_NAME }}.azurewebsites.net"
      
      - name: 'Deploy Frontend to Azure Web App'
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.FRONTEND_APP_NAME }}
          images: '${{ env.ACR_NAME }}.azurecr.io/frontend:${{ env.ENV_TAG }}-${{ github.run_number }}'